//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FncControl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FncControl.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable attach.
        /// </summary>
        internal static string EnableAttach {
            get {
                return ResourceManager.GetString("EnableAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable attack.
        /// </summary>
        internal static string EnableAttack {
            get {
                return ResourceManager.GetString("EnableAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable buy.
        /// </summary>
        internal static string EnableBuy {
            get {
                return ResourceManager.GetString("EnableBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable draw.
        /// </summary>
        internal static string EnableDraw {
            get {
                return ResourceManager.GetString("EnableDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable spell.
        /// </summary>
        internal static string EnableSpell {
            get {
                return ResourceManager.GetString("EnableSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable summon.
        /// </summary>
        internal static string EnableSummon {
            get {
                return ResourceManager.GetString("EnableSummon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable time control.
        /// </summary>
        internal static string EnableTimeControlText {
            get {
                return ResourceManager.GetString("EnableTimeControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game settings.
        /// </summary>
        internal static string GameBehaviorText {
            get {
                return ResourceManager.GetString("GameBehaviorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface settings.
        /// </summary>
        internal static string InterfaceText {
            get {
                return ResourceManager.GetString("InterfaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next rising attribute: .
        /// </summary>
        internal static string NextRisingText {
            get {
                return ResourceManager.GetString("NextRisingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of attachs: .
        /// </summary>
        internal static string NumberOfAttachText {
            get {
                return ResourceManager.GetString("NumberOfAttachText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of attacks: .
        /// </summary>
        internal static string NumberOfAttackText {
            get {
                return ResourceManager.GetString("NumberOfAttackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of buys: .
        /// </summary>
        internal static string NumberOfBuyText {
            get {
                return ResourceManager.GetString("NumberOfBuyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of drawing: .
        /// </summary>
        internal static string NumberOfDrawText {
            get {
                return ResourceManager.GetString("NumberOfDrawText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of spells: .
        /// </summary>
        internal static string NumberOfSpellText {
            get {
                return ResourceManager.GetString("NumberOfSpellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of summons: .
        /// </summary>
        internal static string NumberOfSummonText {
            get {
                return ResourceManager.GetString("NumberOfSummonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time settings.
        /// </summary>
        internal static string TimeControlText {
            get {
                return ResourceManager.GetString("TimeControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of the other player: .
        /// </summary>
        internal static string TimeOtherText {
            get {
                return ResourceManager.GetString("TimeOtherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time player one.
        /// </summary>
        internal static string TimePlayer1 {
            get {
                return ResourceManager.GetString("TimePlayer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time player two.
        /// </summary>
        internal static string TimePlayer2 {
            get {
                return ResourceManager.GetString("TimePlayer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of the current player: .
        /// </summary>
        internal static string TimeText {
            get {
                return ResourceManager.GetString("TimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn.
        /// </summary>
        internal static string TurnText {
            get {
                return ResourceManager.GetString("TurnText", resourceCulture);
            }
        }
    }
}
